import React, { useState, useEffect, Fragment } from "react";

import { generateEmojis, getAndSetMirrorAPIToken } from "./api/mirrorAPI.js";
import { zipAndSaveEmojis } from "./api/zipAndSaveEmojis.js";

import { CardList, Explanation } from "./Containers";
import { ImgUploader, Loading, PrimaryButton, Text } from "./Components";
import { Row } from "./Layouts";

import "./styles.css";

function App() {
  // Gets mirror API token
  const [mirrorAPIToken, setMirrorAPIToken] = useState(
    localStorage.getItem("mirrorAPIToken") || ""
  );
  useEffect(() => {
    if (!mirrorAPIToken) getAndSetMirrorAPIToken(setMirrorAPIToken);
  }, [mirrorAPIToken]);

  // Images uploaded by user
  const [uploadedImages, setUploadedImages] = useState([]);
  // Emojis generated by Mirror AI API
  const [emojis, setEmojis] = useState([]);

  // Sets temporary error message
  const [errorMessage, setErrorMessage] = useState("");
  useEffect(() => {
    setTimeout(() => setErrorMessage(""), 4000);
  }, [errorMessage]);

  // Booleans for conditional rendering
  const [landingState, setLandingState] = useState(true);
  const [imagesUploadedState, setImagesUploadedState] = useState(false);
  const [loadingState, setLoadingState] = useState(false);
  const [emojisGeneratedState, setEmojisGeneratedState] = useState(false);

  // Sets conditional rendering booleans based on application state
  useEffect(() => {
    !uploadedImages.length && !emojis.length && !loadingState
      ? setLandingState(true)
      : setLandingState(false);
    uploadedImages.length && !loadingState
      ? setImagesUploadedState(true)
      : setImagesUploadedState(false);
    emojis.length && !loadingState && !uploadedImages.length
      ? setEmojisGeneratedState(true)
      : setEmojisGeneratedState(false);
  }, [emojis, loadingState, uploadedImages]);

  return (
    <div className="App">
      <Text stylesClass="title">{"Make Emojis!"} </Text>
      <ImgUploader onchange={async images => setUploadedImages(images)} />
      {landingState && (
        <Row>
          <Explanation />
        </Row>
      )}
      {errorMessage && <Text stylesClass="error-message">{errorMessage} </Text>}
      {imagesUploadedState && (
        <Fragment>
          <PrimaryButton
            stylesId="button-generate"
            value="Generate"
            handleclick={() =>
              generateEmojis(
                mirrorAPIToken,
                uploadedImages,
                setLoadingState,
                setEmojis,
                setUploadedImages,
                setErrorMessage
              )
            }
          />
          <Row>
            <CardList cards={uploadedImages} />
          </Row>
        </Fragment>
      )}
      {loadingState && (
        <Row>
          <Loading />
        </Row>
      )}
      {emojisGeneratedState && (
        <Fragment>
          <PrimaryButton
            stylesId="button-save"
            handleclick={() => zipAndSaveEmojis(emojis, setErrorMessage)}
            value="Save As Zip"
          />
          <Row>
            <CardList cards={emojis} />
          </Row>
        </Fragment>
      )}
    </div>
  );
}
/* States of UI: Landing, ImagesUploaded, Generating, Generated  E*/

export default App;
